tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "asdf"
brew "coreutils"
brew "git"
brew "gpg"
brew "hub"
brew "mas"
brew "yarn", args: ["ignore-dependencies"]
brew "zsh"

cask "1password"
cask "alfred"
cask "bartender"
cask "browserstacklocal"
cask "charles"
cask "dash"
cask "evernote"
cask "firefox"
cask "google-chrome"
cask "hostbuddy"
cask "iterm2"
cask "slack"
cask "spotify"
cask "tower"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"

mas "OmniFocus", id: 1346203938
